### ISSUE TITLE
[CLI] Allow specifying port

### ISSUE THREAD

**Issue by AnthonyPorthouse** [pomber/git-history#115]
When running in CLI mode, the it assumes that you have port 5000 available, but this may not always be the case.

Therefore we should allow the port to be manually specified either by environment variable or CLI flag such as `--port` or `-p`

**Comment by pomber** [comment]
If the port isn't available it should [automatically pick another](https://github.com/pomber/git-history/blob/master/cli/server.js#L31). Is it not working?

**Comment by OPEN-LJW** [comment]
i think this function not in hurry
