### ISSUE TITLE
enable one-off donation

### ISSUE THREAD

**Issue by zachvalenta** [pomber/git-history#128]
[Open Collective](https://opencollective.com/git-history) only allows recurring; could we have something like [Regex101](https://regex101.com/) with one-off?

**Comment by pomber** [comment]
I see a "Or make a one time donation" in opencollective. have you tried it?

**Comment by zachvalenta** [comment]
totally missed! my bad 🗿

**Comment by zachvalenta** [comment]
just donated :)

**Comment by pomber** [comment]
Awesome. Thanks!
