### ISSUE TITLE
When copying text from git history empty lines are not copied

### ISSUE THREAD

**Issue by pomber** [pomber/git-history#133]
When copying text from git history empty lines are not copied

**Comment by TrevTag** [comment]
[VZ Messages.cpu_resource-2019-04-16-013259.txt](https://github.com/pomber/git-history/files/3128646/VZ.Messages.cpu_resource-2019-04-16-013259.txt)

**Comment by Arminkhodaei** [comment]
> When copying text from git history empty lines are not copied

Hi, The `div` container assigned for each empty line just has to be filled by a `<br>` tag.
