### ISSUE TITLE
Support GitLab & Bitbucket

### ISSUE THREAD

**Issue by alexanderadam** [pomber/git-history#14]
It would be nice to have support for [gitea](https://github.com/go-gitea/gitea/issues) (or the [gogs](https://github.com/gogs/gogs), the fork it inherited from) and/or [gitlab](https://gitlab.com/gitlab-org/gitlab-ce/).

Or, what would be even better because both are open source, even integrate github-history in them.

**Comment by pomber** [comment]
I'll try to add support for gitlab and bigbucket. Not sure about the APIs from other providers, but you can always use the [CLI](https://github.com/pomber/git-history/tree/master/cli) locally.

**Comment by google-mac** [comment]
Looking forward to Bitbucket support!

**Comment by pomber** [comment]
If anyone want to test GitLab support, use gitlab subdomain instead of github: 
https://gitlab.githistory.xyz/inkscape/inkscape/blob/master/src/document-undo.h

**Comment by pomber** [comment]
Bitbucket should work too:  
https://bitbucket.githistory.xyz/pomber/code-surfer/src/master/packages/mdx-deck-code-surfer/package.json

I still need to figure out why private repos sometimes fail.

**Comment by zzmingo** [comment]
This is awesome, any plan for self-hosted gitlab?

**Comment by QGB** [comment]
support coding.net

**Comment by pomber** [comment]
@QGB I'm not familiar with coding.net, but if anyone open a PR for it I'll merge it.
