### ISSUE TITLE
Icon broken after upgrading VSCode to 1.47.0

### ISSUE THREAD

**Issue by wenfangdu** [pomber/git-history#169]
![image](https://user-images.githubusercontent.com/28700378/87378287-15e5dd00-c5c0-11ea-86cc-a54a4a0ed5af.png)

**Comment by pomber** [comment]
are you sure that's the icon from this extension? I don't remember adding it to the source control panel

**Comment by wenfangdu** [comment]
@pomber 
```
  // Specifies where the 'Git: View History' action appears on the title of SCM Providers.
  //  - Inline: Show the 'Git: View History' action on the title of SCM Providers
  //  - More Actions: Show the 'Git: View History' action in the 'More Actions...' menu on the title of SCM Providers
  "gitHistory.sourceCodeProviderIntegrationLocation": "Inline"
```

**Comment by wenfangdu** [comment]
![image](https://user-images.githubusercontent.com/28700378/88284143-7a6f0d80-cd1f-11ea-93a7-049ea6b1cc30.png)
The looking is fixed, however, clicking two icons will both open the history for the same repo,  depending on the current active file. e.g. if the active file is in the User repo, click either icon will open the history for User repo.

**Comment by pomber** [comment]
Confirmed, that icon isn't from this extension.

**Comment by wenfangdu** [comment]
AH, sorry😳, wrong repo. It's [this one](https://github.com/DonJayamanne/gitHistoryVSCode)
