### ISSUE TITLE
Create browser extension based on this

### ISSUE THREAD

**Issue by rgoliveira** [pomber/git-history#29]
It would be really neat to have this as a Chrome extension. This way I believe it would be possible to use this in private repos, and I guess it could be faster too.

**Comment by pomber** [comment]
This would be awesome. I have very limited experience with extensions and don't have the "bandwidth" right now to work on this.  
If anyone can help with it let me know so we can sync.

**Comment by DeeplyDiligent** [comment]
I develop chrome extensions! What would you like it to do? I can change the URL for you or, I can make the entire app offline, etc

**Comment by pomber** [comment]
Awesome @DeeplyDiligent . Maybe we should start with just a button that changes the URL.

**Comment by DeeplyDiligent** [comment]
Yep definitely! So far I have it working so that it redirects when you click on the extension icon at the top right. Btw, I'm a little new to this GitHub thing.  Do I make a fork of the repository for the extension?

**Comment by DenVys** [comment]
@DeeplyDiligent if you want to add new functionality to project you have to fork it
just push fork button at the main page of this project (near the stars counter)
and if you need help with extension i can help you

**Comment by pomber** [comment]
For now you can create a new repo for the extension, we can copy it later to this one (I need to make this one a monorepo).  
If you need inspiration for adding the button, the extension I mentioned is from @SaraVieira. Maybe it's open sourced somewhere?

**Comment by DeeplyDiligent** [comment]
Yep, the button is quite easy to make, its just injecting a script onto the page. I have created a fork of the project. Currently stuck with the routing (the main page works, the routing does not). You can try it by dragging the /build folder in the root directory into chrome after cloning  and running npm install && npm build in the repo here:https://github.com/DeeplyDiligent/github-history-extension

**Comment by DeeplyDiligent** [comment]
Hi Guys! A preliminary version of the extension is up! Right now, no code is being injected yet, and you must click the button on the top right to activate it 😄 You can get the extension here: https://chrome.google.com/webstore/detail/github-history/akchjlfcomljejobobpiiefpaimhhnmp

**Comment by GMaiolo** [comment]
@pomber would be a good idea for you to create an empty repository and hold the extension code as well, we can fork from there an PR bit by bit.

**Comment by DeeplyDiligent** [comment]
Just letting you guys know, as described before, the extension now shows a  button on each github file page as well. Let me know if you would like me to move the code elsewhere so its easier to make PRs etc.

**Comment by LuisReinoso** [comment]
Hi!
I added a button on github file view, source code is here. [https://github.com/LuisReinoso/github-history-browser-extension](https://github.com/LuisReinoso/github-history-browser-extension)

I published on firefox extensions. 
[https://addons.mozilla.org/es/firefox/addon/github-history/](https://addons.mozilla.org/es/firefox/addon/github-history/)

**Comment by pomber** [comment]
Wow, thanks @DeeplyDiligent  and @LuisReinoso !

@DeeplyDiligent  are you including the app code inside the extension? You need to update the extension every time the app changes? 

Regarding the repository, I think it's ok if the extensions have their own repos and maintainers.

**Comment by pomber** [comment]
@DeeplyDiligent , @LuisReinoso I'm going to change the name of the project to Git History, and the url to https://github.githistory.xyz  

I'm letting you know so you can update the extensions (to use the new url which already works) and maybe rename them.  

(I'm renaming the project so it sounds less official and to make it easier to support gitlab and others)

**Comment by LuisReinoso** [comment]
Hi @pomber.
I'm going to change to new url, the name of extension could be **Git history**. Button on file view will be **Open in Git History**. Are you agree?.

**Comment by pomber** [comment]
Yep, sounds good (use "Title Case" for the name of the extension: "Git History" instead of "Git history")

**Comment by DeeplyDiligent** [comment]
Hi @pomber, I have put the react app onto the extension, which is why it loads much faster than having it on a website. I can pull new changes into my repository and compile it again once you update the repo. Also, let me know your thoughts on this logo: https://github.com/DeeplyDiligent/github-history-extension/blob/master/public/logo.png
