### ISSUE TITLE
[BUG] File not found

### ISSUE THREAD

**Issue by codehz** [pomber/git-history#58]
Example: https://github-history.netlify.com/codehz/StoneServer/blob/master/.gitmodules

**Comment by codehz** [comment]
the actual file: https://github.com/codehz/StoneServer/blob/master/.gitmodules

**Comment by matt-watson90** [comment]
Interesting is that it's only 1 commit that it can't find: ac6da570cadb08d2875d765a51ac51ddfc15fde8

That commit deleted the file. I wonder if that's what is causing it problems?

**Comment by pomber** [comment]
An easy fix would be to use an empty string as the content of any commit that returns 404. It's not perfect but maybe good enough.

**Comment by wjkang** [comment]
I also have the same issue

https://github.com/dotnetcore/surging/blob/master/src/Surging.Services/Surging.Services.Client/Program.cs

https://github.githistory.xyz/dotnetcore/surging/blob/master/src/Surging.Services/Surging.Services.Client/Program.cs

**Comment by Arminkhodaei** [comment]
Is it sensible to get each of the commits status using this:
https://developer.github.com/v3/repos/commits/#get-a-single-commit
And checking the files array in the response for either the file status is **"deleted"** or not? Would be more api calls reasonable?

**Comment by pomber** [comment]
Should be fixed now. Thanks @Arminkhodaei
