### ISSUE TITLE
[BUG] character overflow bug

### ISSUE THREAD

**Issue by codehz** [pomber/git-history#59]
#21 ( https://github-history.netlify.com/llyer/leetcode/blob/master/README.md )
current:
![image](https://user-images.githubusercontent.com/13158903/52481720-4024b580-2bea-11e9-8bd0-c4b822b0cd7f.png)
expected:
![image](https://user-images.githubusercontent.com/13158903/52481734-4dda3b00-2bea-11e9-816e-6a8f039e32f7.png)
Font: Source Han Sans CN, FuraCode Nerd Font Mono

Seems it is a bug about the fonts... 
BTW, height(actual) == font-size is not always true....

**Comment by codehz** [comment]
a possible solution: remove the hardcoded css ` height: 15px`

**Comment by pomber** [comment]
Thanks @codehz .
This is related to #16, the fix is the same, read the line height from the DOM instead of using 15px (sounds easy but it requires a change on how the animation works).
