### ISSUE TITLE
How to deploy ?

### ISSUE THREAD

**Issue by mritd** [pomber/git-history#66]
I tried to wrap this project as a docker image, in fact it was able to run, but since I was using my own domain name; I had a problem with Github OAuth2 authorization:

The page always prompts me to log in to Github (OAuth2 authorization). When I click the button, I am prompted to authorize the success, but the page does not reflect anything; I observed that the authorization callback address does not seem to be my own domain name.

**Comment by mritd** [comment]
I have created a dockerfile and now it looks fine (if the Github public api request limit is not reached);

refs:  #67

**Comment by pomber** [comment]
It's doing oauth through Netlify, I don't belive that part can be selfhosted.  

If you want to make it work you need to create a 
1. create a GitHub oauth app 
2. create a site on Netlify
3. add the github app client id and client secret to the netlify site
4. set the site id form netlify in src/github.js

**Comment by mritd** [comment]
Netlify access is slow in China due to firewall reasons.
Is there a solution that can no longer rely on Netlify?
For example, running git-history on vps.
