### ISSUE TITLE
update changes

### ISSUE THREAD

**Issue by aWhver** [pomber/git-history#74]
Collaborative projects pull other people's new code without seeing the latest changes

**Comment by pomber** [comment]
Hey @aWhver , I don't understand the issue. Do you have an example?

**Comment by aWhver** [comment]
> Hey @aWhver , I don't understand the issue. Do you have an example?

When my colleague pushed the new code to the Repository, I pulled it down and looked at the record. There was no latest change in running it from the command line.

**Comment by pomber** [comment]
You ran the command again after pulling the changes? Or kept it running from before pulling the changes?

**Comment by aWhver** [comment]
I ran the command after pulling the changes.It is strange that  it only showed my initialized records about  files

**Comment by pomber** [comment]
Could you try to reproduce it again and give me more concrete reproduction steps?
