### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by teresaejunior** [pomber/git-history#75]
It would be awesome to have this as a VS Code extension. Is it possible?

**Comment by pomber** [comment]
Yesss, I'm working on this

**Comment by pomber** [comment]
Just published the first version. Anyone want to test it? 
https://marketplace.visualstudio.com/items?itemName=pomber.git-file-history

**Comment by kguidonimartins** [comment]
Works like a charm!

**Comment by teresaejunior** [comment]
Works perfectly! Thank you!

**Comment by bjaroszewska** [comment]
Unfortunately:  Unable to install 'pomber.git-file-history'; there is no available version compatible with VS Code '1.25.1
