### ISSUE TITLE
Firefox extension button not appearing

### ISSUE THREAD

**Issue by peterbe** [pomber/git-history#77]
I've installed the extension and even restarted my Firefox Nightly but no button :( 
Or am I just blind?

<img width="1461" alt="screen shot 2019-02-12 at 12 13 47 pm" src="https://user-images.githubusercontent.com/26739/52654363-cf1e2000-2ebf-11e9-83f6-d3d3c0f20270.png">

Or am I misunderstand the instructions?
<img width="974" alt="screen shot 2019-02-12 at 12 15 10 pm" src="https://user-images.githubusercontent.com/26739/52654477-0c82ad80-2ec0-11e9-9a5d-ffee55d731af.png">

**Comment by pomber** [comment]
Hey @peterbe , the extension repository is: https://github.com/LuisReinoso/git-history-browser-extension, maintained by @LuisReinoso
