### ISSUE TITLE
[CLI] Only display part of git history

### ISSUE THREAD

**Issue by Kamicloud** [pomber/git-history#81]
![image](https://user-images.githubusercontent.com/10206616/52702193-b6dcfc80-2fb6-11e9-8b40-0539a35ab2f9.png)
Above is real git history displayed by tortoise.
When I use 

> git-file-history Application/DataService/Logic/RefundLogic.class.php

can only display 2 commit records in 2016
![image](https://user-images.githubusercontent.com/10206616/52702266-ca886300-2fb6-11e9-8b8d-ce6a5e0ede30.png)

**Comment by pomber** [comment]
Do you have more info? 
This is using the CLI, right?
Anything strange with the missing commits? 
Is it just one file or everyone?

**Comment by Kamicloud** [comment]
> Do you have more info?
> This is using the CLI, right?
> Anything strange with the missing commits?
> Is it just one file or everyone?

I'm using CLI, and tried use

> git log --follow --reverse --date=iso FILE

only display 2 records

> git log --follow --date=iso FILE
can view all commit logs by press ↑ and ↓

Maybe it is a git issue, but I dont know how to solve it

**Comment by Kamicloud** [comment]
> Do you have more info?
> This is using the CLI, right?
> Anything strange with the missing commits?
> Is it just one file or everyone?

Finally I found it caused by --follow option

> git --no-pager log --reverse --date=iso FILE

Sometimes --follow not in a good performance.

Shall we make --follow as optional which can controlled by user? I will be pressure to do that

**Comment by twslade** [comment]
I am seeing missing commits for moved files, but I believe this is caused by a [known bug](http://git.661346.n2.nabble.com/follow-is-ignored-when-used-with-reverse-td7586844.html) when utilizing `--follow` and `--reverse`

**Comment by pomber** [comment]
I think we'll drop --follow for now

**Comment by pomber** [comment]
Could you try with the new version? `npx git-file-history@0.0.4 your/file`

**Comment by twslade** [comment]
Works for me, but not for showing renamed file in history.

Is there a possibility for adding something like the following for showing renamed files? I think that could be very useful with an older codebase. Maybe its an edge case.
```sh
git log --name-only --pretty="format:"  --follow <filename> | sort -u | xargs git log --reverse --
```

[Credit](https://stackoverflow.com/questions/35379277/why-does-git-log-with-follow-and-reverse-return-only-last-commit) for command

**Comment by Kamicloud** [comment]
> Could you try with the new version? `npx git-file-history@0.0.4 your/file`

It works, and I think --follow be controlled by user better.
