### ISSUE TITLE
Unexpected error when tried to load a *.bat file in a private repository.

### ISSUE THREAD

**Issue by vilemj-Viclick** [pomber/git-history#93]
This is what I got, when I tried on a random file in a private repo in our organization (github entity).
![image](https://user-images.githubusercontent.com/13902120/52837925-12130a00-30f1-11e9-8907-4bf844bed178.png)
I mean I didn't expect it to work, but it says to report the issue, so here I am.

I tried a different file in the same repository, and now it says this:
![image](https://user-images.githubusercontent.com/13902120/52837987-57373c00-30f1-11e9-89d1-b32e7f1be737.png)

This leads me to being a bit more specific. The exact URL i tried is:
https://github.githistory.xyz/KenticoInternal/draft-client/blob/master/autostart.bat

To be clear, there is 'some' history with this file:
![image](https://user-images.githubusercontent.com/13902120/52838132-e17fa000-30f1-11e9-9002-79762c76c316.png)

**Comment by pomber** [comment]
Thanks. Do you want to try to fix it? Here's a PR solving it for other file extensions: #82

**Comment by co16353sidak** [comment]
Would love to work on this if no one else is. @pomber @vilemj-Viclick

**Comment by pomber** [comment]
All yours. Let me know if you need help

**Comment by co16353sidak** [comment]
Roger that. @pomber let me give this a try and get back at you 👍

**Comment by co16353sidak** [comment]
@pomber 

Going through the issue, code base and the link provided i have observed that there is present a test and a regex for the `.bat` file extension.
Which makes me think that this is not an issue related to the PR you have linked.
Is there any general direction in which you would like to point me towards if you have a fix in mind.
Thanks a lot in advance.

**Comment by pomber** [comment]
The language returned should match one of the languages from prism: https://github.com/PrismJS/prism/tree/master/components. (`"batch"` maybe?)
